# image base
FROM python:3.7.2-alpine

# establecido directorio de trabajo
WORKDIR /usr/src/app

# copiando e instalando requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copiando app
COPY . /usr/src/app

# ejecutar server
CMD python manage.py run -h 0.0.0.0
